import '@/theme/css/theme.scss';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import Navbar from '@/components/Navbar';
import { ReactNode, Suspense } from 'react';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import App from './App';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body style={{ margin: 0 }}>
        <Suspense fallback={<div>Loading...</div>}>
          <AppRouterCacheProvider options={{ key: 'css' }}>
            <App>
              <Navbar />
              <div>{children}</div>
            </App>
          </AppRouterCacheProvider>
        </Suspense>
      </body>
    </html>
  );
}
